nodeLinker: pnp

packageExtensions:
  "@monorepo/monorepo@*":
    dependencies:
      "vite": "*"
  "@monorepo/monorepo-e2e@*":
    dependencies:
      "@playwright/test": "*"
  "vite@*":
    peerDependencies:
      "rollup": "*"